[package]
name        = "legion-server"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "legion"
path = "src/main.rs"

[features]
default     = ["wasm"]
distributed = ["legion-store/distributed", "hiqlite"]
wasm        = ["legion-runtime/extism"]

[dependencies]
legion-core    = { path = "../legion-core" }
legion-store   = { path = "../legion-store" }
legion-loop    = { path = "../legion-loop" }
legion-cluster   = { path = "../legion-cluster" }
legion-deploy    = { path = "../legion-deploy" }
legion-namespace = { path = "../legion-namespace" }
legion-runtime   = { path = "../legion-runtime" }

hiqlite     = { workspace = true, optional = true }
base64      = { workspace = true }
clap        = { workspace = true }
reqwest     = { workspace = true }
futures          = { workspace = true }
tokio            = { workspace = true }
anyhow           = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
toml             = { workspace = true }
tracing          = { workspace = true }
tracing-subscriber = { workspace = true }
async-trait = { workspace = true }
axum        = { workspace = true }
tower-http       = { workspace = true }
uuid             = { workspace = true }
chrono           = { workspace = true }
